### ISSUE TITLE
有人适配安卓9的吗？

### ISSUE THREAD

**Issue by longhuan1999** [Coconutat/HuaweiP10-GSI-And-Modify-Tutorial#1]

**Comment by Coconutat** [comment]
说清楚。不要留下个标题。详细具体到设备和目的。

**Comment by longhuan1999** [comment]
这是我的解决方案：https://github.com/tiann/KernelSU/discussions/956#discussioncomment-7031296
目前我做出的修改的稳定性和兼容性还不确定

**Comment by Coconutat** [comment]
> 这是我的解决方案：[tiann/KernelSU#956 (comment)](https://github.com/tiann/KernelSU/discussions/956#discussioncomment-7031296) 目前我做出的修改的稳定性和兼容性还不确定

我在测试，感谢大佬指点。我在用我的华为和小米8测试。一个安卓9一个安卓13.

**Comment by Coconutat** [comment]
> 这是我的解决方案：[tiann/KernelSU#956 (comment)](https://github.com/tiann/KernelSU/discussions/956#discussioncomment-7031296) 目前我做出的修改的稳定性和兼容性还不确定

希望你不介意，我重新命名了函数名：https://github.com/tiann/KernelSU/compare/main...Coconutat:KernelSU_Exp:Android_9
我尝试使其命名规范化，然后如果没问题，PR到上游。我会PR给你，你再PR给上游。

**Comment by longhuan1999** [comment]
好的，没问题

**Comment by longhuan1999** [comment]
刚反应过来，你就是那篇讨论的发起人

**Comment by Coconutat** [comment]
> 刚反应过来，你就是那篇讨论的发起人

是啊LoL

**Comment by Coconutat** [comment]
> 刚反应过来，你就是那篇讨论的发起人

![Snipaste_2023-09-18_21-10-45](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/01830f19-10c1-4bdb-b8d4-888a0bb88442)
![Snipaste_2023-09-18_21-10-49](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/4849222d-8d0d-4113-ba35-935357eeddcc)
![Snipaste_2023-09-18_21-10-55](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/dde2c4a6-f271-450f-93a9-d2d27ebf1323)
![Snipaste_2023-09-18_21-11-04](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/
![Snipaste_2023-09-18_21-11-51](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/b8d69aa5-cd5a-4214-885f-47f2d2004ffe)
85353552/6187c4a2-64a6-4849-843b-c481907875b3)
![Snipaste_2023-09-18_21-11-51](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/4c7c51ec-81f0-4cd8-b037-ba0587d37f53)
![Snipaste_2023-09-18_21-12-51](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/21fb2d5d-d764-42fc-a5ce-57ceb38b033f)
![Snipaste_2023-09-18_21-12-59](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/f4836ff6-1cde-4044-840c-7950f6c3d8fb)
![Snipaste_2023-09-18_21-13-05](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/090bcd1a-9a3d-459e-b346-0a1800d4c23e)
![Snipaste_2023-09-18_21-13-27](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/ab5ee065-71ba-4acc-a2c6-ca08a34cd8ee)
![Snipaste_2023-09-18_21-16-06](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/85353552/a7a9401d-e26e-4b4f-93dd-1eddde057b2e)

**Comment by Coconutat** [comment]
> 刚反应过来，你就是那篇讨论的发起人

测试了下两台机子，一个安卓9，一个安卓13，工作都很正常。
