### ISSUE TITLE
华为 p40 990 5g 可以永久解 BL 嘛

### ISSUE THREAD

**Issue by sherlcok314159** [Coconutat/HuaweiP10-GSI-And-Modify-Tutorial#2]
如题
![Screenshot_20240429_083006_com android settings](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/76043326/8d36fb4e-c6a5-40f6-bbbd-dc6fafa8ac5b)
![Screenshot_20240429_083010_com android settings](https://github.com/Coconutat/Huawei-GSI-And-Modify-Or-Support-KernelSU-Tutorial/assets/76043326/7b0b3585-91e0-4939-bc88-02e647367ab5)

**Comment by Coconutat** [comment]
> 如题 ![Screenshot_20240429_083006_com android settings](https://private-user-images.githubusercontent.com/76043326/327022039-8d36fb4e-c6a5-40f6-bbbd-dc6fafa8ac5b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Nzg0NzEsIm5iZiI6MTcxNDU3ODE3MSwicGF0aCI6Ii83NjA0MzMyNi8zMjcwMjIwMzktOGQzNmZiNGUtYzZhNS00MGY2LWJiYmQtZGM2ZmFmYThhYzViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE1NDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNjdiMTNmYmYzNTE3NDE1MWFlNDZiZWFlNDljNGFhMTJhYWYyNjMxYWQ0NjBmOTY5ZjdkOWU3MDNmMzZhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.llcYnOF43gURBWKFuqimT4vMPbZAc2S69Bi0cFSUnZ0) ![Screenshot_20240429_083010_com android settings](https://private-user-images.githubusercontent.com/76043326/327022042-7b0b3585-91e0-4939-bc88-02e647367ab5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Nzg0NzEsIm5iZiI6MTcxNDU3ODE3MSwicGF0aCI6Ii83NjA0MzMyNi8zMjcwMjIwNDItN2IwYjM1ODUtOTFlMC00OTM5LWJjODgtMDJlNjQ3MzY3YWI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE1NDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMDMwZjk4ZmE4YmU4MjMwZTFjYTE1YTM0MjJkNzNkYTVlMTk0NDg0Y2ExNWJjOWJhZmJmNTUyMjdmMmQ5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPyAqBdUQLRjCWGDPj8VuxXRrRky8lW5s5F9tbZ3eYE)

可能这么说不太好，想要解锁基本上如下：要么入职华为，要么自己足够强研究。或者未来有人研究如何解锁。
  
再或者有渠道去购买对应型号的工程机，工程机本就就是解锁的。
